---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
spec:
  chart:
    spec:
      chart: vault
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: infrastructure
  interval: 1h0m0s
  timeout: 10m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
      existingConfigMap: config
      replicaCount: 3
      pdb:
        create: true
        minAvailable: 1
    persistence:
      enabled: true
