---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - helmrelease.yaml

configMapGenerator:
- name: config
  files:
  - unseal.hcl=unseal.hcl
  - vault.hcl=vault.hcl
  - inmem-storage.hcl=inmem-storage.hcl
#  - raft.hcl=raft.hcl
